# Generated by Django 4.2 on 2023-05-14 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#FFFFFF', 'White'), ('#FFFF99', 'Yellow'), ('#CCFF33', 'Green'), ('#66CCFF', 'Blue'), ('#FF9933', 'Orange')], default=('#FFFFFF', 'White'), max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('date_only', models.BooleanField(default=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notesapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivation_date', models.DateField(default=datetime.date(2023, 5, 14))),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesapp.note')),
            ],
        ),
    ]
